server:
  port: 8082
  servlet:
    context-path: /cloud-product

spring:
  application:
    name: cloud-product

#eureka配置
eureka:
  node1: http://security:security@localhost:9091/eureka
  node2: http://security:security@localhost:9092/eureka
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.node1},${eureka.node2}

#feign配置
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 2000
        read-timeout: 20000

#actuator监控配置
management:
  server:
    port: 8888
    ssl:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  security:
    enabled: true
security:
  user:
    name: admin
    password: 123456