server:
  port: 9092

#security安全验证配置
spring:
  application:
    name: eureka-server-two
  security:
    basic: true
    user:
      name: security
      password: security

#eureka集群配置
eureka:
  instance:                         #开启ip注册
    prefer-ip-address: true
    ip-address: localhost
  client:                           #开启eureka集群模式
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://security:security@localhost:9091/eureka
  server:                           #方便测试关闭自我保护机制
    enable-self-preservation: false